### ISSUE TITLE
submodule address

### ISSUE THREAD

**Issue by portaloffreedom** [nathanielw/Material-Icons-for-Pencil#1]
Hi!
I just wrote an [archlinux package](https://aur.archlinux.org/packages/pencil-material-icons-git/) for this project. I had to do a workaround to download it because of the submodule.
The reason is simple: the submodules are registered as git@github.com....  This requires a registered key and a github account. It would be much better for everyone if you just change the remote address to the http version, so it's possible to download the project without forcing someone to create a github account or do dirty tricks. 

Cheers

**Comment by nathanielw** [comment]
Oh, thanks for pointing that out and cheers for creating an AUR package! Push incoming with the submodule URL changed...
